/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as PlacementRouteImport } from './routes/placement'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ArticlesIndexRouteImport } from './routes/articles.index'
import { Route as ArticlesSlugRouteImport } from './routes/articles.$slug'
import { Route as EnIndexRouteImport } from './routes/en/index'
import { Route as EnAboutRouteImport } from './routes/en/about'
import { Route as EnBookingRouteImport } from './routes/en/booking'
import { Route as EnCoursesRouteImport } from './routes/en/courses'
import { Route as EnPlacementRouteImport } from './routes/en/placement'
import { Route as EnArticlesIndexRouteImport } from './routes/en/articles.index'
import { Route as EnArticlesSlugRouteImport } from './routes/en/articles.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacementRoute = PlacementRouteImport.update({
  id: '/placement',
  path: '/placement',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/en/',
  path: '/en/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnAboutRoute = EnAboutRouteImport.update({
  id: '/en/about',
  path: '/en/about',
  getParentRoute: () => rootRouteImport,
} as any)
const EnBookingRoute = EnBookingRouteImport.update({
  id: '/en/booking',
  path: '/en/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const EnCoursesRoute = EnCoursesRouteImport.update({
  id: '/en/courses',
  path: '/en/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const EnPlacementRoute = EnPlacementRouteImport.update({
  id: '/en/placement',
  path: '/en/placement',
  getParentRoute: () => rootRouteImport,
} as any)
const EnArticlesIndexRoute = EnArticlesIndexRouteImport.update({
  id: '/en/articles/',
  path: '/en/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnArticlesSlugRoute = EnArticlesSlugRouteImport.update({
  id: '/en/articles/$slug',
  path: '/en/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking': typeof BookingRoute
  '/courses': typeof CoursesRoute
  '/placement': typeof PlacementRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/en/about': typeof EnAboutRoute
  '/en/booking': typeof EnBookingRoute
  '/en/courses': typeof EnCoursesRoute
  '/en/placement': typeof EnPlacementRoute
  '/articles/': typeof ArticlesIndexRoute
  '/en/': typeof EnIndexRoute
  '/en/articles/$slug': typeof EnArticlesSlugRoute
  '/en/articles/': typeof EnArticlesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking': typeof BookingRoute
  '/courses': typeof CoursesRoute
  '/placement': typeof PlacementRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/en/about': typeof EnAboutRoute
  '/en/booking': typeof EnBookingRoute
  '/en/courses': typeof EnCoursesRoute
  '/en/placement': typeof EnPlacementRoute
  '/articles': typeof ArticlesIndexRoute
  '/en': typeof EnIndexRoute
  '/en/articles/$slug': typeof EnArticlesSlugRoute
  '/en/articles': typeof EnArticlesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking': typeof BookingRoute
  '/courses': typeof CoursesRoute
  '/placement': typeof PlacementRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/en/about': typeof EnAboutRoute
  '/en/booking': typeof EnBookingRoute
  '/en/courses': typeof EnCoursesRoute
  '/en/placement': typeof EnPlacementRoute
  '/articles/': typeof ArticlesIndexRoute
  '/en/': typeof EnIndexRoute
  '/en/articles/$slug': typeof EnArticlesSlugRoute
  '/en/articles/': typeof EnArticlesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/booking'
    | '/courses'
    | '/placement'
    | '/sitemap.xml'
    | '/articles/$slug'
    | '/en/about'
    | '/en/booking'
    | '/en/courses'
    | '/en/placement'
    | '/articles/'
    | '/en/'
    | '/en/articles/$slug'
    | '/en/articles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/booking'
    | '/courses'
    | '/placement'
    | '/sitemap.xml'
    | '/articles/$slug'
    | '/en/about'
    | '/en/booking'
    | '/en/courses'
    | '/en/placement'
    | '/articles'
    | '/en'
    | '/en/articles/$slug'
    | '/en/articles'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/booking'
    | '/courses'
    | '/placement'
    | '/sitemap.xml'
    | '/articles/$slug'
    | '/en/about'
    | '/en/booking'
    | '/en/courses'
    | '/en/placement'
    | '/articles/'
    | '/en/'
    | '/en/articles/$slug'
    | '/en/articles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookingRoute: typeof BookingRoute
  CoursesRoute: typeof CoursesRoute
  PlacementRoute: typeof PlacementRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  EnAboutRoute: typeof EnAboutRoute
  EnBookingRoute: typeof EnBookingRoute
  EnCoursesRoute: typeof EnCoursesRoute
  EnPlacementRoute: typeof EnPlacementRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
  EnIndexRoute: typeof EnIndexRoute
  EnArticlesSlugRoute: typeof EnArticlesSlugRoute
  EnArticlesIndexRoute: typeof EnArticlesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/placement': {
      id: '/placement'
      path: '/placement'
      fullPath: '/placement'
      preLoaderRoute: typeof PlacementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/en'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/about': {
      id: '/en/about'
      path: '/en/about'
      fullPath: '/en/about'
      preLoaderRoute: typeof EnAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/booking': {
      id: '/en/booking'
      path: '/en/booking'
      fullPath: '/en/booking'
      preLoaderRoute: typeof EnBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/courses': {
      id: '/en/courses'
      path: '/en/courses'
      fullPath: '/en/courses'
      preLoaderRoute: typeof EnCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/placement': {
      id: '/en/placement'
      path: '/en/placement'
      fullPath: '/en/placement'
      preLoaderRoute: typeof EnPlacementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/articles/': {
      id: '/en/articles/'
      path: '/en/articles'
      fullPath: '/en/articles/'
      preLoaderRoute: typeof EnArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/articles/$slug': {
      id: '/en/articles/$slug'
      path: '/en/articles/$slug'
      fullPath: '/en/articles/$slug'
      preLoaderRoute: typeof EnArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookingRoute: BookingRoute,
  CoursesRoute: CoursesRoute,
  PlacementRoute: PlacementRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ArticlesSlugRoute: ArticlesSlugRoute,
  EnAboutRoute: EnAboutRoute,
  EnBookingRoute: EnBookingRoute,
  EnCoursesRoute: EnCoursesRoute,
  EnPlacementRoute: EnPlacementRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
  EnIndexRoute: EnIndexRoute,
  EnArticlesSlugRoute: EnArticlesSlugRoute,
  EnArticlesIndexRoute: EnArticlesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
