/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as PlacementRouteImport } from './routes/placement'
import { Route as EnIndexRouteImport } from './routes/en/index'
import { Route as EnAboutRouteImport } from './routes/en/about'
import { Route as EnBookingRouteImport } from './routes/en/booking'
import { Route as EnCoursesRouteImport } from './routes/en/courses'
import { Route as EnPlacementRouteImport } from './routes/en/placement'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacementRoute = PlacementRouteImport.update({
  id: '/placement',
  path: '/placement',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/en/',
  path: '/en/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnAboutRoute = EnAboutRouteImport.update({
  id: '/en/about',
  path: '/en/about',
  getParentRoute: () => rootRouteImport,
} as any)
const EnBookingRoute = EnBookingRouteImport.update({
  id: '/en/booking',
  path: '/en/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const EnCoursesRoute = EnCoursesRouteImport.update({
  id: '/en/courses',
  path: '/en/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const EnPlacementRoute = EnPlacementRouteImport.update({
  id: '/en/placement',
  path: '/en/placement',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking': typeof BookingRoute
  '/courses': typeof CoursesRoute
  '/placement': typeof PlacementRoute
  '/en/about': typeof EnAboutRoute
  '/en/booking': typeof EnBookingRoute
  '/en/courses': typeof EnCoursesRoute
  '/en/placement': typeof EnPlacementRoute
  '/en/': typeof EnIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking': typeof BookingRoute
  '/courses': typeof CoursesRoute
  '/placement': typeof PlacementRoute
  '/en/about': typeof EnAboutRoute
  '/en/booking': typeof EnBookingRoute
  '/en/courses': typeof EnCoursesRoute
  '/en/placement': typeof EnPlacementRoute
  '/en': typeof EnIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking': typeof BookingRoute
  '/courses': typeof CoursesRoute
  '/placement': typeof PlacementRoute
  '/en/about': typeof EnAboutRoute
  '/en/booking': typeof EnBookingRoute
  '/en/courses': typeof EnCoursesRoute
  '/en/placement': typeof EnPlacementRoute
  '/en/': typeof EnIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/booking'
    | '/courses'
    | '/placement'
    | '/en/about'
    | '/en/booking'
    | '/en/courses'
    | '/en/placement'
    | '/en/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/booking'
    | '/courses'
    | '/placement'
    | '/en/about'
    | '/en/booking'
    | '/en/courses'
    | '/en/placement'
    | '/en'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/booking'
    | '/courses'
    | '/placement'
    | '/en/about'
    | '/en/booking'
    | '/en/courses'
    | '/en/placement'
    | '/en/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookingRoute: typeof BookingRoute
  CoursesRoute: typeof CoursesRoute
  PlacementRoute: typeof PlacementRoute
  EnAboutRoute: typeof EnAboutRoute
  EnBookingRoute: typeof EnBookingRoute
  EnCoursesRoute: typeof EnCoursesRoute
  EnPlacementRoute: typeof EnPlacementRoute
  EnIndexRoute: typeof EnIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/placement': {
      id: '/placement'
      path: '/placement'
      fullPath: '/placement'
      preLoaderRoute: typeof PlacementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/en'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/about': {
      id: '/en/about'
      path: '/en/about'
      fullPath: '/en/about'
      preLoaderRoute: typeof EnAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/booking': {
      id: '/en/booking'
      path: '/en/booking'
      fullPath: '/en/booking'
      preLoaderRoute: typeof EnBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/courses': {
      id: '/en/courses'
      path: '/en/courses'
      fullPath: '/en/courses'
      preLoaderRoute: typeof EnCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/placement': {
      id: '/en/placement'
      path: '/en/placement'
      fullPath: '/en/placement'
      preLoaderRoute: typeof EnPlacementRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookingRoute: BookingRoute,
  CoursesRoute: CoursesRoute,
  PlacementRoute: PlacementRoute,
  EnAboutRoute: EnAboutRoute,
  EnBookingRoute: EnBookingRoute,
  EnCoursesRoute: EnCoursesRoute,
  EnPlacementRoute: EnPlacementRoute,
  EnIndexRoute: EnIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
