/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as InstructorRouteImport } from './routes/instructor'
import { Route as PlacementRouteImport } from './routes/placement'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ArticlesIndexRouteImport } from './routes/articles.index'
import { Route as ArticlesSlugRouteImport } from './routes/articles.$slug'
import { Route as EnIndexRouteImport } from './routes/en/index'
import { Route as EnAboutRouteImport } from './routes/en/about'
import { Route as EnBookingRouteImport } from './routes/en/booking'
import { Route as EnCoursesRouteImport } from './routes/en/courses'
import { Route as EnDashboardRouteImport } from './routes/en.dashboard'
import { Route as EnInstructorRouteImport } from './routes/en.instructor'
import { Route as EnPlacementRouteImport } from './routes/en/placement'
import { Route as EnSignInRouteImport } from './routes/en.sign-in'
import { Route as EnSignUpRouteImport } from './routes/en.sign-up'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as EnArticlesIndexRouteImport } from './routes/en/articles.index'
import { Route as EnArticlesSlugRouteImport } from './routes/en/articles.$slug'
import { Route as EnSignInSplatRouteImport } from './routes/en.sign-in.$'
import { Route as EnSignUpSplatRouteImport } from './routes/en.sign-up.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorRoute = InstructorRouteImport.update({
  id: '/instructor',
  path: '/instructor',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacementRoute = PlacementRouteImport.update({
  id: '/placement',
  path: '/placement',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/en/',
  path: '/en/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnAboutRoute = EnAboutRouteImport.update({
  id: '/en/about',
  path: '/en/about',
  getParentRoute: () => rootRouteImport,
} as any)
const EnBookingRoute = EnBookingRouteImport.update({
  id: '/en/booking',
  path: '/en/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const EnCoursesRoute = EnCoursesRouteImport.update({
  id: '/en/courses',
  path: '/en/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const EnDashboardRoute = EnDashboardRouteImport.update({
  id: '/en/dashboard',
  path: '/en/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EnInstructorRoute = EnInstructorRouteImport.update({
  id: '/en/instructor',
  path: '/en/instructor',
  getParentRoute: () => rootRouteImport,
} as any)
const EnPlacementRoute = EnPlacementRouteImport.update({
  id: '/en/placement',
  path: '/en/placement',
  getParentRoute: () => rootRouteImport,
} as any)
const EnSignInRoute = EnSignInRouteImport.update({
  id: '/en/sign-in',
  path: '/en/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const EnSignUpRoute = EnSignUpRouteImport.update({
  id: '/en/sign-up',
  path: '/en/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => SignInRoute,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => SignUpRoute,
} as any)
const EnArticlesIndexRoute = EnArticlesIndexRouteImport.update({
  id: '/en/articles/',
  path: '/en/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnArticlesSlugRoute = EnArticlesSlugRouteImport.update({
  id: '/en/articles/$slug',
  path: '/en/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EnSignInSplatRoute = EnSignInSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => EnSignInRoute,
} as any)
const EnSignUpSplatRoute = EnSignUpSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => EnSignUpRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking': typeof BookingRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/instructor': typeof InstructorRoute
  '/placement': typeof PlacementRoute
  '/sign-in': typeof SignInRouteWithChildren
  '/sign-up': typeof SignUpRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/en/about': typeof EnAboutRoute
  '/en/booking': typeof EnBookingRoute
  '/en/courses': typeof EnCoursesRoute
  '/en/dashboard': typeof EnDashboardRoute
  '/en/instructor': typeof EnInstructorRoute
  '/en/placement': typeof EnPlacementRoute
  '/en/sign-in': typeof EnSignInRouteWithChildren
  '/en/sign-up': typeof EnSignUpRouteWithChildren
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/articles/': typeof ArticlesIndexRoute
  '/en/': typeof EnIndexRoute
  '/en/articles/$slug': typeof EnArticlesSlugRoute
  '/en/sign-in/$': typeof EnSignInSplatRoute
  '/en/sign-up/$': typeof EnSignUpSplatRoute
  '/en/articles/': typeof EnArticlesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking': typeof BookingRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/instructor': typeof InstructorRoute
  '/placement': typeof PlacementRoute
  '/sign-in': typeof SignInRouteWithChildren
  '/sign-up': typeof SignUpRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/en/about': typeof EnAboutRoute
  '/en/booking': typeof EnBookingRoute
  '/en/courses': typeof EnCoursesRoute
  '/en/dashboard': typeof EnDashboardRoute
  '/en/instructor': typeof EnInstructorRoute
  '/en/placement': typeof EnPlacementRoute
  '/en/sign-in': typeof EnSignInRouteWithChildren
  '/en/sign-up': typeof EnSignUpRouteWithChildren
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/articles': typeof ArticlesIndexRoute
  '/en': typeof EnIndexRoute
  '/en/articles/$slug': typeof EnArticlesSlugRoute
  '/en/sign-in/$': typeof EnSignInSplatRoute
  '/en/sign-up/$': typeof EnSignUpSplatRoute
  '/en/articles': typeof EnArticlesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking': typeof BookingRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/instructor': typeof InstructorRoute
  '/placement': typeof PlacementRoute
  '/sign-in': typeof SignInRouteWithChildren
  '/sign-up': typeof SignUpRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/en/about': typeof EnAboutRoute
  '/en/booking': typeof EnBookingRoute
  '/en/courses': typeof EnCoursesRoute
  '/en/dashboard': typeof EnDashboardRoute
  '/en/instructor': typeof EnInstructorRoute
  '/en/placement': typeof EnPlacementRoute
  '/en/sign-in': typeof EnSignInRouteWithChildren
  '/en/sign-up': typeof EnSignUpRouteWithChildren
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/articles/': typeof ArticlesIndexRoute
  '/en/': typeof EnIndexRoute
  '/en/articles/$slug': typeof EnArticlesSlugRoute
  '/en/sign-in/$': typeof EnSignInSplatRoute
  '/en/sign-up/$': typeof EnSignUpSplatRoute
  '/en/articles/': typeof EnArticlesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/booking'
    | '/courses'
    | '/dashboard'
    | '/instructor'
    | '/placement'
    | '/sign-in'
    | '/sign-up'
    | '/sitemap.xml'
    | '/articles/$slug'
    | '/en/about'
    | '/en/booking'
    | '/en/courses'
    | '/en/dashboard'
    | '/en/instructor'
    | '/en/placement'
    | '/en/sign-in'
    | '/en/sign-up'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/articles/'
    | '/en/'
    | '/en/articles/$slug'
    | '/en/sign-in/$'
    | '/en/sign-up/$'
    | '/en/articles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/booking'
    | '/courses'
    | '/dashboard'
    | '/instructor'
    | '/placement'
    | '/sign-in'
    | '/sign-up'
    | '/sitemap.xml'
    | '/articles/$slug'
    | '/en/about'
    | '/en/booking'
    | '/en/courses'
    | '/en/dashboard'
    | '/en/instructor'
    | '/en/placement'
    | '/en/sign-in'
    | '/en/sign-up'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/articles'
    | '/en'
    | '/en/articles/$slug'
    | '/en/sign-in/$'
    | '/en/sign-up/$'
    | '/en/articles'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/booking'
    | '/courses'
    | '/dashboard'
    | '/instructor'
    | '/placement'
    | '/sign-in'
    | '/sign-up'
    | '/sitemap.xml'
    | '/articles/$slug'
    | '/en/about'
    | '/en/booking'
    | '/en/courses'
    | '/en/dashboard'
    | '/en/instructor'
    | '/en/placement'
    | '/en/sign-in'
    | '/en/sign-up'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/articles/'
    | '/en/'
    | '/en/articles/$slug'
    | '/en/sign-in/$'
    | '/en/sign-up/$'
    | '/en/articles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookingRoute: typeof BookingRoute
  CoursesRoute: typeof CoursesRoute
  DashboardRoute: typeof DashboardRoute
  InstructorRoute: typeof InstructorRoute
  PlacementRoute: typeof PlacementRoute
  SignInRoute: typeof SignInRouteWithChildren
  SignUpRoute: typeof SignUpRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  EnAboutRoute: typeof EnAboutRoute
  EnBookingRoute: typeof EnBookingRoute
  EnCoursesRoute: typeof EnCoursesRoute
  EnDashboardRoute: typeof EnDashboardRoute
  EnInstructorRoute: typeof EnInstructorRoute
  EnPlacementRoute: typeof EnPlacementRoute
  EnSignInRoute: typeof EnSignInRouteWithChildren
  EnSignUpRoute: typeof EnSignUpRouteWithChildren
  ArticlesIndexRoute: typeof ArticlesIndexRoute
  EnIndexRoute: typeof EnIndexRoute
  EnArticlesSlugRoute: typeof EnArticlesSlugRoute
  EnArticlesIndexRoute: typeof EnArticlesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor': {
      id: '/instructor'
      path: '/instructor'
      fullPath: '/instructor'
      preLoaderRoute: typeof InstructorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/placement': {
      id: '/placement'
      path: '/placement'
      fullPath: '/placement'
      preLoaderRoute: typeof PlacementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/en'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/about': {
      id: '/en/about'
      path: '/en/about'
      fullPath: '/en/about'
      preLoaderRoute: typeof EnAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/booking': {
      id: '/en/booking'
      path: '/en/booking'
      fullPath: '/en/booking'
      preLoaderRoute: typeof EnBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/courses': {
      id: '/en/courses'
      path: '/en/courses'
      fullPath: '/en/courses'
      preLoaderRoute: typeof EnCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/dashboard': {
      id: '/en/dashboard'
      path: '/en/dashboard'
      fullPath: '/en/dashboard'
      preLoaderRoute: typeof EnDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/instructor': {
      id: '/en/instructor'
      path: '/en/instructor'
      fullPath: '/en/instructor'
      preLoaderRoute: typeof EnInstructorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/placement': {
      id: '/en/placement'
      path: '/en/placement'
      fullPath: '/en/placement'
      preLoaderRoute: typeof EnPlacementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/sign-in': {
      id: '/en/sign-in'
      path: '/en/sign-in'
      fullPath: '/en/sign-in'
      preLoaderRoute: typeof EnSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/sign-up': {
      id: '/en/sign-up'
      path: '/en/sign-up'
      fullPath: '/en/sign-up'
      preLoaderRoute: typeof EnSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof SignInRoute
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof SignUpRoute
    }
    '/en/articles/': {
      id: '/en/articles/'
      path: '/en/articles'
      fullPath: '/en/articles/'
      preLoaderRoute: typeof EnArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/articles/$slug': {
      id: '/en/articles/$slug'
      path: '/en/articles/$slug'
      fullPath: '/en/articles/$slug'
      preLoaderRoute: typeof EnArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/sign-in/$': {
      id: '/en/sign-in/$'
      path: '/$'
      fullPath: '/en/sign-in/$'
      preLoaderRoute: typeof EnSignInSplatRouteImport
      parentRoute: typeof EnSignInRoute
    }
    '/en/sign-up/$': {
      id: '/en/sign-up/$'
      path: '/$'
      fullPath: '/en/sign-up/$'
      preLoaderRoute: typeof EnSignUpSplatRouteImport
      parentRoute: typeof EnSignUpRoute
    }
  }
}

interface SignInRouteChildren {
  SignInSplatRoute: typeof SignInSplatRoute
}

const SignInRouteChildren: SignInRouteChildren = {
  SignInSplatRoute: SignInSplatRoute,
}

const SignInRouteWithChildren =
  SignInRoute._addFileChildren(SignInRouteChildren)

interface SignUpRouteChildren {
  SignUpSplatRoute: typeof SignUpSplatRoute
}

const SignUpRouteChildren: SignUpRouteChildren = {
  SignUpSplatRoute: SignUpSplatRoute,
}

const SignUpRouteWithChildren =
  SignUpRoute._addFileChildren(SignUpRouteChildren)

interface EnSignInRouteChildren {
  EnSignInSplatRoute: typeof EnSignInSplatRoute
}

const EnSignInRouteChildren: EnSignInRouteChildren = {
  EnSignInSplatRoute: EnSignInSplatRoute,
}

const EnSignInRouteWithChildren = EnSignInRoute._addFileChildren(
  EnSignInRouteChildren,
)

interface EnSignUpRouteChildren {
  EnSignUpSplatRoute: typeof EnSignUpSplatRoute
}

const EnSignUpRouteChildren: EnSignUpRouteChildren = {
  EnSignUpSplatRoute: EnSignUpSplatRoute,
}

const EnSignUpRouteWithChildren = EnSignUpRoute._addFileChildren(
  EnSignUpRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookingRoute: BookingRoute,
  CoursesRoute: CoursesRoute,
  DashboardRoute: DashboardRoute,
  InstructorRoute: InstructorRoute,
  PlacementRoute: PlacementRoute,
  SignInRoute: SignInRouteWithChildren,
  SignUpRoute: SignUpRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ArticlesSlugRoute: ArticlesSlugRoute,
  EnAboutRoute: EnAboutRoute,
  EnBookingRoute: EnBookingRoute,
  EnCoursesRoute: EnCoursesRoute,
  EnDashboardRoute: EnDashboardRoute,
  EnInstructorRoute: EnInstructorRoute,
  EnPlacementRoute: EnPlacementRoute,
  EnSignInRoute: EnSignInRouteWithChildren,
  EnSignUpRoute: EnSignUpRouteWithChildren,
  ArticlesIndexRoute: ArticlesIndexRoute,
  EnIndexRoute: EnIndexRoute,
  EnArticlesSlugRoute: EnArticlesSlugRoute,
  EnArticlesIndexRoute: EnArticlesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
